services:
  azerisiq:
    image: azerisiq
    build:
      context: .
      dockerfile: AzerIsiq/Dockerfile
    container_name: azerisiq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sql;Database=AzerIsiqDB;User Id=SA;Password=MyStrongPass123;Encrypt=true;TrustServerCertificate=True
    ports:
      - "5252:5252"
    networks:
      - azerisiq_default

volumes:
  sqlserver-data:
    driver: local

networks:
  azerisiq_default:
    external: true
