services:
  azerisiq:
    image: azerisiq
    build:
      context: .
      dockerfile: AzerIsiq/Dockerfile
    container_name: azerisiq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sql;Database=AzerIsiqDB;User Id=SA;Password=MyStrongPass123;Encrypt=true;TrustServerCertificate=True
    ports:
      - "5252:5252"
    networks:
      - azerisiq_default
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
        
        
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123@
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  sqlserver-data:
    driver: local
  pgdata:

networks:
  azerisiq_default:
    external: true